describe('Scorecard user flow', () => {

  beforeEach(() => {
    cy.visit('http://localhost:3000/')
      .get('.search-btn').click()
  });

  it('should be able to add players to a round', () => {
    cy.get('.course-card').eq(0).click()

    cy.get('input').type('main{enter}')

    cy.get('.choose-course-btn').click()
    cy.get('input').type('Phil{enter}')
    cy.get('input').type('Evan{enter}')
      .get('.start-round-btn').click()
      .get('.minus-btn').eq(0).click()
      .get('p').contains('2')
      .get('.plus-btn').eq(1).click()
      .get('p').contains('4')
      .get('.next-hole-btn').click()
      .get('.minus-btn').eq(0).click()
      .get('.plus-btn').eq(1).click()
      .get('.next-hole-btn').click()
      .get('.minus-btn').eq(0).click()
      .get('.plus-btn').eq(1).click()
      .get('.next-hole-btn').click()
      .get('.minus-btn').eq(0).click()
      .get('.plus-btn').eq(1).click()
      .get('.next-hole-btn').click()
      .get('.minus-btn').eq(0).click()
      .get('.plus-btn').eq(1).click()
      .get('.next-hole-btn').click()
      .get('.minus-btn').eq(0).click()
      .get('.plus-btn').eq(1).click()
      .get('.next-hole-btn').click()
      .get('.minus-btn').eq(0).click()
      .get('.plus-btn').eq(1).click()
      .get('.next-hole-btn').click()
      .get('.minus-btn').eq(0).click()
      .get('.plus-btn').eq(1).click()
      .get('.next-hole-btn').click()
      .get('.minus-btn').eq(0).click()
      .get('.plus-btn').eq(1).click()
      .get('.next-hole-btn').click()
      .get('.minus-btn').eq(0).click()
      .get('.plus-btn').eq(1).click()
      .get('.next-hole-btn').click()
      .get('.minus-btn').eq(0).click()
      .get('.plus-btn').eq(1).click()
      .get('.next-hole-btn').click()
      .get('.minus-btn').eq(0).click()
      .get('.plus-btn').eq(1).click()
      .get('.next-hole-btn').click()
      .get('.minus-btn').eq(0).click()
      .get('.plus-btn').eq(1).click()
      .get('.end-round-btn').click()

    cy.get('.round-par')
    cy.get('.round-date')
    cy.get('h2').contains('Johnson & Wales University')
    cy.get('h3').eq(0).contains('Phil')
    cy.get('.player-total').eq(0).contains('14')
    cy.get('.player-score').eq(0).contains('-25')
    cy.get('h3').eq(1).contains('Evan')
    cy.get('.player-total').eq(1).contains('130')
    cy.get('.player-score').eq(1).contains('91')
  })

})
